/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sicalne1;

import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */

public class PAGO extends javax.swing.JFrame {

    /**
     * Creates new form PAGO
     */
    public PAGO() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/sicalne1/SICALNE-LOGO.JPG")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_ht = new javax.swing.JTextField();
        txt_sb = new javax.swing.JTextField();
        txt_st = new javax.swing.JTextField();
        txt_dsp = new javax.swing.JTextField();
        txt_sn = new javax.swing.JTextField();
        txt_ph = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_sbto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("HORAS TRABAJADAS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(32, 121, 130, 30);

        jLabel3.setText("VALOR HORA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 123, 140, 40);

        jLabel4.setText("SUELDO BASICO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(32, 165, 130, 20);

        jLabel5.setText("TRANSPORTE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 200, 190, 22);

        jLabel6.setText("SUELDO NETO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(32, 314, 86, 13);

        jLabel7.setText("DESCUENTOSYP");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(32, 277, 291, 19);

        txt_ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_htActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ht);
        txt_ht.setBounds(210, 130, 90, 30);
        getContentPane().add(txt_sb);
        txt_sb.setBounds(210, 170, 90, 30);
        getContentPane().add(txt_st);
        txt_st.setBounds(210, 201, 90, 30);
        getContentPane().add(txt_dsp);
        txt_dsp.setBounds(210, 260, 90, 30);
        getContentPane().add(txt_sn);
        txt_sn.setBounds(210, 290, 90, 30);
        getContentPane().add(txt_ph);
        txt_ph.setBounds(450, 120, 85, 40);

        btn_calcular.setText("CALCULAR");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcular);
        btn_calcular.setBounds(32, 339, 110, 21);

        btn_nuevo.setText("NUEVO");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo);
        btn_nuevo.setBounds(180, 340, 90, 21);

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir);
        btn_salir.setBounds(300, 340, 89, 21);

        jLabel8.setText("SUELDO BRUTO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(32, 228, 150, 30);
        getContentPane().add(txt_sbto);
        txt_sbto.setBounds(210, 230, 90, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sicalne1/SICALNE-LOGO.JPG"))); // NOI18N
        jLabel9.setText("SICALNE 1.0");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 20, 360, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_htActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_htActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_htActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        double horasTrabajadas, tarifaHorario, sueldobasico, transporte,sueldobruto, sueldoneto, descuentosyp;
        
        horasTrabajadas =  Double.parseDouble(txt_ht.getText());
        tarifaHorario = Double.parseDouble(txt_ph.getText());         
        
        sueldobasico = horasTrabajadas * tarifaHorario ;
        transporte= 97032 ;
        sueldobruto = sueldobasico+transporte;
        descuentosyp = sueldobruto/100 * 8;
        sueldoneto= sueldobruto-descuentosyp;    
        
        txt_sb.setText(String.valueOf(sueldobasico));
        txt_st.setText(String.valueOf(transporte)) ;      
        txt_dsp.setText(String.valueOf(descuentosyp));
        txt_sn.setText(String.valueOf(sueldoneto));
        txt_sbto.setText(String.valueOf(sueldobruto));
        
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        txt_ht.setText("");
        txt_sb.setText("");
        txt_st.setText("");      
        txt_dsp.setText("");
        txt_sn.setText("");
        txt_sbto.setText("");
        txt_ph.setText("");
         txt_ht.requestFocus();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PAGO().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_dsp;
    private javax.swing.JTextField txt_ht;
    private javax.swing.JTextField txt_ph;
    private javax.swing.JTextField txt_sb;
    private javax.swing.JTextField txt_sbto;
    private javax.swing.JTextField txt_sn;
    private javax.swing.JTextField txt_st;
    // End of variables declaration//GEN-END:variables

}
